import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import { ConfigService } from '@nestjs/config';
import { 
  Inventory, 
  InventoryMovement, 
  Warehouse, 
  Area,
  GoodsReceipt,
  GoodsReceiptItem,
  GoodsIssue,
  GoodsIssueItem,
  InventoryTransferRequest,
  TransferRequestItem,
  InventoryTransfer,
  TransferItem,
  InventoryCounting,
  CountingItem,
  InventoryPosting,
  PostingItem,
  InventoryRevaluation,
  RevaluationItem
} from '../entities';

export const getTypeOrmConfig = (configService: ConfigService): TypeOrmModuleOptions => ({
  type: 'mysql',
  host: configService.get<string>('DB_HOST')!,
  port: configService.get<number>('DB_PORT')!,
  username: configService.get<string>('DB_USERNAME')!,
  password: configService.get<string>('DB_PASSWORD')!,
  database: configService.get<string>('DB_DATABASE')!,
  entities: [
    Inventory, 
    InventoryMovement, 
    Warehouse, 
    Area,
    GoodsReceipt,
    GoodsReceiptItem,
    GoodsIssue,
    GoodsIssueItem,
    InventoryTransferRequest,
    TransferRequestItem,
    InventoryTransfer,
    TransferItem,
    InventoryCounting,
    CountingItem,
    InventoryPosting,
    PostingItem,
    InventoryRevaluation,
    RevaluationItem
  ],
  synchronize: false, // Disabled to prevent ALTER TABLE on startup
  logging: configService.get<string>('NODE_ENV') === 'development',
  migrations: ['dist/infrastructure/database/migrations/*.js'],
  migrationsRun: false,
  timezone: '+07:00',
  charset: 'utf8mb4',
  extra: {
    connectionLimit: 10,
    acquireTimeout: 60000,
    timeout: 60000,
  },
});

export const typeOrmConfig: TypeOrmModuleOptions = {
  type: 'mysql',
  host: process.env.DB_HOST!,
  port: parseInt(process.env.DB_PORT!),
  username: process.env.DB_USERNAME!,
  password: process.env.DB_PASSWORD!,
  database: process.env.DB_DATABASE!,
  entities: [
    Inventory, 
    InventoryMovement, 
    Warehouse, 
    Area,
    GoodsReceipt,
    GoodsReceiptItem,
    GoodsIssue,
    GoodsIssueItem,
    InventoryTransferRequest,
    TransferRequestItem,
    InventoryTransfer,
    TransferItem,
    InventoryCounting,
    CountingItem,
    InventoryPosting,
    PostingItem,
    InventoryRevaluation,
    RevaluationItem
  ],
  synchronize: false, // Disabled to prevent ALTER TABLE on startup
  logging: process.env.NODE_ENV === 'development',
  migrations: ['dist/infrastructure/database/migrations/*.js'],
  migrationsRun: false,
  timezone: '+07:00',
  charset: 'utf8mb4',
  extra: {
    connectionLimit: 10,
    acquireTimeout: 60000,
    timeout: 60000,
  },
};
