export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum InvoiceType {
  SALES = 'SALES',
  PURCHASE = 'PURCHASE',
  CREDIT_NOTE = 'CREDIT_NOTE',
  DEBIT_NOTE = 'DEBIT_NOTE',
}

export class Invoice {
  constructor(
    public readonly id: string,
    public readonly invoiceNumber: string,
    public readonly type: InvoiceType,
    public readonly status: InvoiceStatus,
    public readonly customerId: string,
    public readonly customerName: string,
    public readonly customerEmail?: string,
    public readonly customerAddress?: string,
    public readonly customerTaxCode?: string,
    public readonly orderId?: string,
    public readonly orderNumber?: string,
    public readonly invoiceDate: Date = new Date(),
    public readonly dueDate: Date = new Date(),
    public readonly subtotal: number = 0,
    public readonly taxAmount: number = 0,
    public readonly discountAmount: number = 0,
    public readonly totalAmount: number = 0,
    public readonly paidAmount: number = 0,
    public readonly balanceAmount: number = 0,
    public readonly currency: string = 'USD',
    public readonly exchangeRate: number = 1,
    public readonly notes?: string,
    public readonly termsConditions?: string,
    public readonly createdBy?: string,
    public readonly sentBy?: string,
    public readonly sentAt?: Date,
    public readonly paidBy?: string,
    public readonly paidAt?: Date,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
  ) {}

  static create(
    invoiceNumber: string,
    type: InvoiceType,
    customerId: string,
    customerName: string,
    invoiceDate: Date,
    dueDate: Date,
    customerEmail?: string,
    customerAddress?: string,
    customerTaxCode?: string,
    orderId?: string,
    orderNumber?: string,
    notes?: string,
    termsConditions?: string,
    createdBy?: string,
  ): Invoice {
    return new Invoice(
      '', // Will be set by repository
      invoiceNumber,
      type,
      InvoiceStatus.DRAFT,
      customerId,
      customerName,
      customerEmail,
      customerAddress,
      customerTaxCode,
      orderId,
      orderNumber,
      invoiceDate,
      dueDate,
      0,
      0,
      0,
      0,
      0,
      0,
      'USD',
      1,
      notes,
      termsConditions,
      createdBy,
    );
  }

  updateAmounts(
    subtotal: number,
    taxAmount: number,
    discountAmount: number,
    totalAmount: number,
  ): Invoice {
    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      this.status,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      subtotal,
      taxAmount,
      discountAmount,
      totalAmount,
      this.paidAmount,
      totalAmount - this.paidAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      this.sentBy,
      this.sentAt,
      this.paidBy,
      this.paidAt,
      this.createdAt,
      new Date(),
    );
  }

  markAsSent(sentBy: string): Invoice {
    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      InvoiceStatus.SENT,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      this.subtotal,
      this.taxAmount,
      this.discountAmount,
      this.totalAmount,
      this.paidAmount,
      this.balanceAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      sentBy,
      new Date(),
      this.paidBy,
      this.paidAt,
      this.createdAt,
      new Date(),
    );
  }

  markAsPaid(paidBy: string, paidAmount: number): Invoice {
    const newPaidAmount = this.paidAmount + paidAmount;
    const newBalanceAmount = this.totalAmount - newPaidAmount;
    const newStatus = newBalanceAmount <= 0 ? InvoiceStatus.PAID : this.status;

    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      newStatus,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      this.subtotal,
      this.taxAmount,
      this.discountAmount,
      this.totalAmount,
      newPaidAmount,
      newBalanceAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      this.sentBy,
      this.sentAt,
      paidBy,
      new Date(),
      this.createdAt,
      new Date(),
    );
  }

  markAsOverdue(): Invoice {
    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      InvoiceStatus.OVERDUE,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      this.subtotal,
      this.taxAmount,
      this.discountAmount,
      this.totalAmount,
      this.paidAmount,
      this.balanceAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      this.sentBy,
      this.sentAt,
      this.paidBy,
      this.paidAt,
      this.createdAt,
      new Date(),
    );
  }

  cancel(): Invoice {
    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      InvoiceStatus.CANCELLED,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      this.subtotal,
      this.taxAmount,
      this.discountAmount,
      this.totalAmount,
      this.paidAmount,
      this.balanceAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      this.sentBy,
      this.sentAt,
      this.paidBy,
      this.paidAt,
      this.createdAt,
      new Date(),
    );
  }

  recordPayment(paymentAmount: number, paidBy?: string): Invoice {
    const newPaidAmount = (this.paidAmount || 0) + paymentAmount;
    const newStatus = newPaidAmount >= this.totalAmount ? InvoiceStatus.PAID : this.status;
    const newPaidAt = newStatus === InvoiceStatus.PAID ? new Date() : this.paidAt;
    
    return new Invoice(
      this.id,
      this.invoiceNumber,
      this.type,
      newStatus,
      this.customerId,
      this.customerName,
      this.customerEmail,
      this.customerAddress,
      this.customerTaxCode,
      this.orderId,
      this.orderNumber,
      this.invoiceDate,
      this.dueDate,
      this.subtotal,
      this.taxAmount,
      this.discountAmount,
      this.totalAmount,
      newPaidAmount,
      this.totalAmount - newPaidAmount,
      this.currency,
      this.exchangeRate,
      this.notes,
      this.termsConditions,
      this.createdBy,
      this.sentBy,
      this.sentAt,
      paidBy || this.paidBy,
      newPaidAt,
      this.createdAt,
      new Date(),
    );
  }
}
