-- HR Service Database Migration Script
-- Run this script to create all HR tables

-- 1. Create cat_employee_status table
CREATE TABLE IF NOT EXISTS cat_employee_status (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description text NULL,
    is_active tinyint(1) NULL DEFAULT '1',
    sort_order int NULL DEFAULT '0',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
);

-- 2. Create cat_contract_types table
CREATE TABLE IF NOT EXISTS cat_contract_types (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description text NULL,
    is_active tinyint(1) NULL DEFAULT '1',
    sort_order int NULL DEFAULT '0',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
);

-- 3. Create cat_leave_types table
CREATE TABLE IF NOT EXISTS cat_leave_types (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description text NULL,
    is_paid tinyint(1) NULL DEFAULT '1',
    max_days_per_year int NULL,
    requires_approval tinyint(1) NULL DEFAULT '1',
    is_active tinyint(1) NULL DEFAULT '1',
    sort_order int NULL DEFAULT '0',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
);

-- 4. Create cat_attendance_types table
CREATE TABLE IF NOT EXISTS cat_attendance_types (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description text NULL,
    is_active tinyint(1) NULL DEFAULT '1',
    sort_order int NULL DEFAULT '0',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
);

-- 5. Create departments table
CREATE TABLE IF NOT EXISTS departments (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(200) NOT NULL,
    display_name varchar(200) NOT NULL,
    description text NULL,
    parent_id int NULL,
    manager_id int NULL COMMENT 'FK to employees.id - Trưởng phòng',
    budget decimal(15,2) NULL DEFAULT '0.00',
    is_active tinyint(1) NULL DEFAULT '1',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES departments(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_parent_id (parent_id),
    INDEX idx_manager_id (manager_id),
    INDEX idx_is_active (is_active)
);

-- 6. Create positions table
CREATE TABLE IF NOT EXISTS positions (
    id int NOT NULL auto_increment,
    code varchar(20) NOT NULL,
    name varchar(200) NOT NULL,
    display_name varchar(200) NOT NULL,
    description text NULL,
    level int NULL DEFAULT '1' COMMENT 'Cấp bậc: 1=Junior, 2=Middle, 3=Senior, 4=Lead, 5=Manager',
    requirements text NULL COMMENT 'Yêu cầu công việc',
    is_active tinyint(1) NULL DEFAULT '1',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_level (level),
    INDEX idx_is_active (is_active)
);

-- 7. Create employees table
CREATE TABLE IF NOT EXISTS employees (
    id int NOT NULL auto_increment,
    employee_code varchar(50) NOT NULL COMMENT 'Mã nhân viên',
    user_id int NULL COMMENT 'FK to users.id - Liên kết với tài khoản hệ thống',
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    full_name varchar(200) GENERATED ALWAYS AS (CONCAT(first_name, ' ', last_name)) STORED,
    gender enum('MALE','FEMALE','OTHER') NULL,
    date_of_birth date NULL,
    place_of_birth varchar(200) NULL,
    id_card_number varchar(20) NULL,
    id_card_issued_date date NULL,
    id_card_issued_place varchar(200) NULL,
    permanent_address text NULL COMMENT 'Địa chỉ thường trú',
    temporary_address text NULL COMMENT 'Địa chỉ tạm trú',
    city varchar(100) NULL,
    province varchar(100) NULL,
    country varchar(100) NULL DEFAULT 'Vietnam',
    postal_code varchar(20) NULL,
    phone varchar(20) NULL,
    email varchar(255) NULL,
    emergency_contact_name varchar(200) NULL,
    emergency_contact_phone varchar(20) NULL,
    emergency_contact_relationship varchar(100) NULL,
    department_id int NULL COMMENT 'FK to departments.id',
    position_id int NULL COMMENT 'FK to positions.id',
    manager_id int NULL COMMENT 'FK to employees.id - Quản lý trực tiếp',
    hire_date date NOT NULL COMMENT 'Ngày vào làm',
    probation_end_date date NULL COMMENT 'Ngày kết thúc thử việc',
    resignation_date date NULL COMMENT 'Ngày nghỉ việc',
    status_id int NULL COMMENT 'FK to cat_employee_status.id',
    contract_type_id int NULL COMMENT 'FK to cat_contract_types.id',
    base_salary decimal(15,2) NULL DEFAULT '0.00',
    currency varchar(3) NULL DEFAULT 'VND',
    avatar_url text NULL,
    notes text NULL,
    is_active tinyint(1) NULL DEFAULT '1',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (position_id) REFERENCES positions(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (manager_id) REFERENCES employees(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (status_id) REFERENCES cat_employee_status(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (contract_type_id) REFERENCES cat_contract_types(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    UNIQUE KEY employee_code (employee_code),
    UNIQUE KEY id_card_number (id_card_number),
    INDEX idx_employee_code (employee_code),
    INDEX idx_user_id (user_id),
    INDEX idx_department_id (department_id),
    INDEX idx_position_id (position_id),
    INDEX idx_manager_id (manager_id),
    INDEX idx_status_id (status_id),
    INDEX idx_hire_date (hire_date),
    INDEX idx_is_active (is_active),
    INDEX idx_full_name (full_name)
);

-- 8. Create contract_legal table
CREATE TABLE IF NOT EXISTS contract_legal (
    id int NOT NULL auto_increment,
    contract_number varchar(50) NOT NULL COMMENT 'Số hợp đồng',
    employee_id int NOT NULL COMMENT 'FK to employees.id',
    contract_type_id int NOT NULL COMMENT 'FK to cat_contract_types.id',
    start_date date NOT NULL COMMENT 'Ngày bắt đầu',
    end_date date NULL COMMENT 'Ngày kết thúc - NULL nếu hợp đồng không xác định thời hạn',
    is_indefinite tinyint(1) NULL DEFAULT '0' COMMENT 'Hợp đồng không xác định thời hạn',
    base_salary decimal(15,2) NOT NULL DEFAULT '0.00',
    allowances decimal(15,2) NULL DEFAULT '0.00' COMMENT 'Phụ cấp',
    bonus decimal(15,2) NULL DEFAULT '0.00' COMMENT 'Thưởng',
    currency varchar(3) NULL DEFAULT 'VND',
    working_hours_per_week int NULL DEFAULT '40',
    probation_period_days int NULL DEFAULT '0',
    signed_date date NULL,
    signed_by_employee tinyint(1) NULL DEFAULT '0',
    signed_by_company tinyint(1) NULL DEFAULT '0',
    company_representative varchar(200) NULL COMMENT 'Người đại diện công ty ký',
    contract_file_url text NULL COMMENT 'Link file hợp đồng',
    status enum('DRAFT','ACTIVE','EXPIRED','TERMINATED','CANCELLED') NULL DEFAULT 'DRAFT',
    terms_conditions text NULL COMMENT 'Điều khoản và điều kiện',
    notes text NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY (contract_type_id) REFERENCES cat_contract_types(id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    UNIQUE KEY contract_number (contract_number),
    INDEX idx_contract_number (contract_number),
    INDEX idx_employee_id (employee_id),
    INDEX idx_contract_type_id (contract_type_id),
    INDEX idx_start_date (start_date),
    INDEX idx_end_date (end_date),
    INDEX idx_status (status)
);

-- 9. Create attendance_records table
CREATE TABLE IF NOT EXISTS attendance_records (
    id int NOT NULL auto_increment,
    employee_id int NOT NULL COMMENT 'FK to employees.id',
    attendance_date date NOT NULL COMMENT 'Ngày chấm công',
    attendance_type_id int NULL COMMENT 'FK to cat_attendance_types.id',
    check_in_time datetime NULL,
    check_out_time datetime NULL,
    break_duration_minutes int NULL DEFAULT '0' COMMENT 'Thời gian nghỉ (phút)',
    working_hours decimal(5,2) NULL COMMENT 'Số giờ làm việc',
    overtime_hours decimal(5,2) NULL DEFAULT '0.00' COMMENT 'Số giờ làm thêm',
    late_minutes int NULL DEFAULT '0' COMMENT 'Số phút đi muộn',
    early_leave_minutes int NULL DEFAULT '0' COMMENT 'Số phút về sớm',
    type enum('WORK','OVERTIME','LEAVE','HOLIDAY','ABSENT','SICK','OTHER') NULL DEFAULT 'WORK',
    status enum('PENDING','APPROVED','REJECTED','CANCELLED') NULL DEFAULT 'PENDING',
    approved_by int NULL COMMENT 'FK to users.id',
    approved_at timestamp NULL,
    rejection_reason text NULL,
    notes text NULL,
    location varchar(255) NULL COMMENT 'Địa điểm chấm công (GPS, địa chỉ)',
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY (attendance_type_id) REFERENCES cat_attendance_types(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    UNIQUE KEY uk_employee_date (employee_id, attendance_date),
    INDEX idx_employee_id (employee_id),
    INDEX idx_attendance_date (attendance_date),
    INDEX idx_type (type),
    INDEX idx_status (status),
    INDEX idx_approved_by (approved_by)
);

-- 10. Create leave_requests table
CREATE TABLE IF NOT EXISTS leave_requests (
    id int NOT NULL auto_increment,
    request_number varchar(50) NOT NULL COMMENT 'Số đơn nghỉ phép',
    employee_id int NOT NULL COMMENT 'FK to employees.id',
    leave_type_id int NOT NULL COMMENT 'FK to cat_leave_types.id',
    start_date date NOT NULL COMMENT 'Ngày bắt đầu',
    end_date date NOT NULL COMMENT 'Ngày kết thúc',
    total_days decimal(5,2) NOT NULL COMMENT 'Tổng số ngày nghỉ',
    is_half_day tinyint(1) NULL DEFAULT '0' COMMENT 'Nghỉ nửa ngày',
    half_day_type enum('MORNING','AFTERNOON') NULL COMMENT 'Nửa ngày sáng hay chiều',
    reason text NOT NULL COMMENT 'Lý do',
    approver_id int NULL COMMENT 'FK to employees.id - Người duyệt',
    status enum('PENDING','APPROVED','REJECTED','CANCELLED') NULL DEFAULT 'PENDING',
    approved_at timestamp NULL,
    rejected_at timestamp NULL,
    rejection_reason text NULL,
    attachment_url text NULL,
    notes text NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    created_by int NULL,
    updated_by int NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY (approver_id) REFERENCES employees(id) ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY (leave_type_id) REFERENCES cat_leave_types(id) ON UPDATE NO ACTION ON DELETE RESTRICT,
    UNIQUE KEY request_number (request_number),
    INDEX idx_request_number (request_number),
    INDEX idx_employee_id (employee_id),
    INDEX idx_leave_type_id (leave_type_id),
    INDEX idx_start_date (start_date),
    INDEX idx_end_date (end_date),
    INDEX idx_status (status),
    INDEX idx_approver_id (approver_id)
);

